using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nuboj.Archiver.ETL.Saver.Models
{
    public class Nvm
    {
        // Guid aggiunto da Andrea Zanetti come PK
        [Key]
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string SensorDataType { get; set; }
        public int LastAlarmTs_9 { get; set; }
        public int LastAlarmCode_9 { get; set; }
        public int LastAlarmTs_8 { get; set; }
        public int LastAlarmCode_8 { get; set; }
        public int LastAlarmTs_7 { get; set; }
        public int LastAlarmCode_7 { get; set; }
        public int LastAlarmTs_6 { get; set; }
        public int LastAlarmCode_6 { get; set; }
        public int LastAlarmTs_5 { get; set; }
        public int LastAlarmCode_5 { get; set; }
        public int LastAlarmTs_4 { get; set; }
        public int LastAlarmCode_4 { get; set; }
        public int LastAlarmTs_3 { get; set; }
        public int LastAlarmCode_3 { get; set; }
        public int LastAlarmTs_2 { get; set; }
        public int LastAlarmCode_2 { get; set; }
        public int LastAlarmTs_1 { get; set; }
        public int LastAlarmCode_1 { get; set; }
        public int LastAlarmTs_0 { get; set; }
        public int LastAlarmCode_0 { get; set; }
        public bool IsCronoEmpty { get; set; }
        public int CRC16_eeprom { get; set; }
        public int cod_compatibilita { get; set; }
        public string pwd_wifi { get; set; }
        public string SSID_wifi { get; set; }
        public double temp_comfort_idro { get; set; }
        public double temp_eco_idro { get; set; }
        public int offs_act_perc { get; set; }
        public int offs_act { get; set; }
        public int n_lim { get; set; }
        public int primo_avvio_scheda { get; set; }
        public int flag_ora_leg { get; set; }
        public string sn_stufa { get; set; }
        public string seed_mqtt { get; set; }
        public int off_sens_pres { get; set; }
        public int cod_banca_dati { get; set; }
        public int tipo_allarme_salv { get; set; }
        public int funz_salv { get; set; }
        public int sub_ope_salv { get; set; }
        public int ope_salv { get; set; }
        public int att { get; set; }
        public int program_g7_int48 { get; set; }
        public int program_g7_int47 { get; set; }
        public int program_g7_int46 { get; set; }
        public int program_g7_int45 { get; set; }
        public int program_g7_int44 { get; set; }
        public int program_g7_int43 { get; set; }
        public int program_g7_int42 { get; set; }
        public int program_g7_int41 { get; set; }
        public int program_g7_int40 { get; set; }
        public int program_g7_int39 { get; set; }
        public int program_g7_int38 { get; set; }
        public int program_g7_int37 { get; set; }
        public int program_g7_int36 { get; set; }
        public int program_g7_int35 { get; set; }
        public int program_g7_int34 { get; set; }
        public int program_g7_int33 { get; set; }
        public int program_g7_int32 { get; set; }
        public int program_g7_int31 { get; set; }
        public int program_g7_int30 { get; set; }
        public int program_g7_int29 { get; set; }
        public int program_g7_int28 { get; set; }
        public int program_g7_int27 { get; set; }
        public int program_g7_int26 { get; set; }
        public int program_g7_int25 { get; set; }
        public int program_g7_int24 { get; set; }
        public int program_g7_int23 { get; set; }
        public int program_g7_int22 { get; set; }
        public int program_g7_int21 { get; set; }
        public int program_g7_int20 { get; set; }
        public int program_g7_int19 { get; set; }
        public int program_g7_int18 { get; set; }
        public int program_g7_int17 { get; set; }
        public int program_g7_int16 { get; set; }
        public int program_g7_int15 { get; set; }
        public int program_g7_int14 { get; set; }
        public int program_g7_int13 { get; set; }
        public int program_g7_int12 { get; set; }
        public int program_g7_int11 { get; set; }
        public int program_g7_int10 { get; set; }
        public int program_g7_int9 { get; set; }
        public int program_g7_int8 { get; set; }
        public int program_g7_int7 { get; set; }
        public int program_g7_int6 { get; set; }
        public int program_g7_int5 { get; set; }
        public int program_g7_int4 { get; set; }
        public int program_g7_int3 { get; set; }
        public int program_g7_int2 { get; set; }
        public int program_g7_int1 { get; set; }
        public int program_g6_int48 { get; set; }
        public int program_g6_int47 { get; set; }
        public int program_g6_int46 { get; set; }
        public int program_g6_int45 { get; set; }
        public int program_g6_int44 { get; set; }
        public int program_g6_int43 { get; set; }
        public int program_g6_int42 { get; set; }
        public int program_g6_int41 { get; set; }
        public int program_g6_int40 { get; set; }
        public int program_g6_int39 { get; set; }
        public int program_g6_int38 { get; set; }
        public int program_g6_int37 { get; set; }
        public int program_g6_int36 { get; set; }
        public int program_g6_int35 { get; set; }
        public int program_g6_int34 { get; set; }
        public int program_g6_int33 { get; set; }
        public int program_g6_int32 { get; set; }
        public int program_g6_int31 { get; set; }
        public int program_g6_int30 { get; set; }
        public int program_g6_int29 { get; set; }
        public int program_g6_int28 { get; set; }
        public int program_g6_int27 { get; set; }
        public int program_g6_int26 { get; set; }
        public int program_g6_int25 { get; set; }
        public int program_g6_int24 { get; set; }
        public int program_g6_int23 { get; set; }
        public int program_g6_int22 { get; set; }
        public int program_g6_int21 { get; set; }
        public int program_g6_int20 { get; set; }
        public int program_g6_int19 { get; set; }
        public int program_g6_int18 { get; set; }
        public int program_g6_int17 { get; set; }
        public int program_g6_int16 { get; set; }
        public int program_g6_int15 { get; set; }
        public int program_g6_int14 { get; set; }
        public int program_g6_int13 { get; set; }
        public int program_g6_int12 { get; set; }
        public int program_g6_int11 { get; set; }
        public int program_g6_int10 { get; set; }
        public int program_g6_int9 { get; set; }
        public int program_g6_int8 { get; set; }
        public int program_g6_int7 { get; set; }
        public int program_g6_int6 { get; set; }
        public int program_g6_int5 { get; set; }
        public int program_g6_int4 { get; set; }
        public int program_g6_int3 { get; set; }
        public int program_g6_int2 { get; set; }
        public int program_g6_int1 { get; set; }
        public int program_g5_int48 { get; set; }
        public int program_g5_int47 { get; set; }
        public int program_g5_int46 { get; set; }
        public int program_g5_int45 { get; set; }
        public int program_g5_int44 { get; set; }
        public int program_g5_int43 { get; set; }
        public int program_g5_int42 { get; set; }
        public int program_g5_int41 { get; set; }
        public int program_g5_int40 { get; set; }
        public int program_g5_int39 { get; set; }
        public int program_g5_int38 { get; set; }
        public int program_g5_int37 { get; set; }
        public int program_g5_int36 { get; set; }
        public int program_g5_int35 { get; set; }
        public int program_g5_int34 { get; set; }
        public int program_g5_int33 { get; set; }
        public int program_g5_int32 { get; set; }
        public int program_g5_int31 { get; set; }
        public int program_g5_int30 { get; set; }
        public int program_g5_int29 { get; set; }
        public int program_g5_int28 { get; set; }
        public int program_g5_int27 { get; set; }
        public int program_g5_int26 { get; set; }
        public int program_g5_int25 { get; set; }
        public int program_g5_int24 { get; set; }
        public int program_g5_int23 { get; set; }
        public int program_g5_int22 { get; set; }
        public int program_g5_int21 { get; set; }
        public int program_g5_int20 { get; set; }
        public int program_g5_int19 { get; set; }
        public int program_g5_int18 { get; set; }
        public int program_g5_int17 { get; set; }
        public int program_g5_int16 { get; set; }
        public int program_g5_int15 { get; set; }
        public int program_g5_int14 { get; set; }
        public int program_g5_int13 { get; set; }
        public int program_g5_int12 { get; set; }
        public int program_g5_int11 { get; set; }
        public int program_g5_int10 { get; set; }
        public int program_g5_int9 { get; set; }
        public int program_g5_int8 { get; set; }
        public int program_g5_int7 { get; set; }
        public int program_g5_int6 { get; set; }
        public int program_g5_int5 { get; set; }
        public int program_g5_int4 { get; set; }
        public int program_g5_int3 { get; set; }
        public int program_g5_int2 { get; set; }
        public int program_g5_int1 { get; set; }
        public int program_g4_int48 { get; set; }
        public int program_g4_int47 { get; set; }
        public int program_g4_int46 { get; set; }
        public int program_g4_int45 { get; set; }
        public int program_g4_int44 { get; set; }
        public int program_g4_int43 { get; set; }
        public int program_g4_int42 { get; set; }
        public int program_g4_int41 { get; set; }
        public int program_g4_int40 { get; set; }
        public int program_g4_int39 { get; set; }
        public int program_g4_int38 { get; set; }
        public int program_g4_int37 { get; set; }
        public int program_g4_int36 { get; set; }
        public int program_g4_int35 { get; set; }
        public int program_g4_int34 { get; set; }
        public int program_g4_int33 { get; set; }
        public int program_g4_int32 { get; set; }
        public int program_g4_int31 { get; set; }
        public int program_g4_int30 { get; set; }
        public int program_g4_int29 { get; set; }
        public int program_g4_int28 { get; set; }
        public int program_g4_int27 { get; set; }
        public int program_g4_int26 { get; set; }
        public int program_g4_int25 { get; set; }
        public int program_g4_int24 { get; set; }
        public int program_g4_int23 { get; set; }
        public int program_g4_int22 { get; set; }
        public int program_g4_int21 { get; set; }
        public int program_g4_int20 { get; set; }
        public int program_g4_int19 { get; set; }
        public int program_g4_int18 { get; set; }
        public int program_g4_int17 { get; set; }
        public int program_g4_int16 { get; set; }
        public int program_g4_int15 { get; set; }
        public int program_g4_int14 { get; set; }
        public int program_g4_int13 { get; set; }
        public int program_g4_int12 { get; set; }
        public int program_g4_int11 { get; set; }
        public int program_g4_int10 { get; set; }
        public int program_g4_int9 { get; set; }
        public int program_g4_int8 { get; set; }
        public int program_g4_int7 { get; set; }
        public int program_g4_int6 { get; set; }
        public int program_g4_int5 { get; set; }
        public int program_g4_int4 { get; set; }
        public int program_g4_int3 { get; set; }
        public int program_g4_int2 { get; set; }
        public int program_g4_int1 { get; set; }
        public int program_g3_int48 { get; set; }
        public int program_g3_int47 { get; set; }
        public int program_g3_int46 { get; set; }
        public int program_g3_int45 { get; set; }
        public int program_g3_int44 { get; set; }
        public int program_g3_int43 { get; set; }
        public int program_g3_int42 { get; set; }
        public int program_g3_int41 { get; set; }
        public int program_g3_int40 { get; set; }
        public int program_g3_int39 { get; set; }
        public int program_g3_int38 { get; set; }
        public int program_g3_int37 { get; set; }
        public int program_g3_int36 { get; set; }
        public int program_g3_int35 { get; set; }
        public int program_g3_int34 { get; set; }
        public int program_g3_int33 { get; set; }
        public int program_g3_int32 { get; set; }
        public int program_g3_int31 { get; set; }
        public int program_g3_int30 { get; set; }
        public int program_g3_int29 { get; set; }
        public int program_g3_int28 { get; set; }
        public int program_g3_int27 { get; set; }
        public int program_g3_int26 { get; set; }
        public int program_g3_int25 { get; set; }
        public int program_g3_int24 { get; set; }
        public int program_g3_int23 { get; set; }
        public int program_g3_int22 { get; set; }
        public int program_g3_int21 { get; set; }
        public int program_g3_int20 { get; set; }
        public int program_g3_int19 { get; set; }
        public int program_g3_int18 { get; set; }
        public int program_g3_int17 { get; set; }
        public int program_g3_int16 { get; set; }
        public int program_g3_int15 { get; set; }
        public int program_g3_int14 { get; set; }
        public int program_g3_int13 { get; set; }
        public int program_g3_int12 { get; set; }
        public int program_g3_int11 { get; set; }
        public int program_g3_int10 { get; set; }
        public int program_g3_int9 { get; set; }
        public int program_g3_int8 { get; set; }
        public int program_g3_int7 { get; set; }
        public int program_g3_int6 { get; set; }
        public int program_g3_int5 { get; set; }
        public int program_g3_int4 { get; set; }
        public int program_g3_int3 { get; set; }
        public int program_g3_int2 { get; set; }
        public int program_g3_int1 { get; set; }
        public int program_g2_int48 { get; set; }
        public int program_g2_int47 { get; set; }
        public int program_g2_int46 { get; set; }
        public int program_g2_int45 { get; set; }
        public int program_g2_int44 { get; set; }
        public int program_g2_int43 { get; set; }
        public int program_g2_int42 { get; set; }
        public int program_g2_int41 { get; set; }
        public int program_g2_int40 { get; set; }
        public int program_g2_int39 { get; set; }
        public int program_g2_int38 { get; set; }
        public int program_g2_int37 { get; set; }
        public int program_g2_int36 { get; set; }
        public int program_g2_int35 { get; set; }
        public int program_g2_int34 { get; set; }
        public int program_g2_int33 { get; set; }
        public int program_g2_int32 { get; set; }
        public int program_g2_int31 { get; set; }
        public int program_g2_int30 { get; set; }
        public int program_g2_int29 { get; set; }
        public int program_g2_int28 { get; set; }
        public int program_g2_int27 { get; set; }
        public int program_g2_int26 { get; set; }
        public int program_g2_int25 { get; set; }
        public int program_g2_int24 { get; set; }
        public int program_g2_int23 { get; set; }
        public int program_g2_int22 { get; set; }
        public int program_g2_int21 { get; set; }
        public int program_g2_int20 { get; set; }
        public int program_g2_int19 { get; set; }
        public int program_g2_int18 { get; set; }
        public int program_g2_int17 { get; set; }
        public int program_g2_int16 { get; set; }
        public int program_g2_int15 { get; set; }
        public int program_g2_int14 { get; set; }
        public int program_g2_int13 { get; set; }
        public int program_g2_int12 { get; set; }
        public int program_g2_int11 { get; set; }
        public int program_g2_int10 { get; set; }
        public int program_g2_int9 { get; set; }
        public int program_g2_int8 { get; set; }
        public int program_g2_int7 { get; set; }
        public int program_g2_int6 { get; set; }
        public int program_g2_int5 { get; set; }
        public int program_g2_int4 { get; set; }
        public int program_g2_int3 { get; set; }
        public int program_g2_int2 { get; set; }
        public int program_g2_int1 { get; set; }
        public int program_g1_int48 { get; set; }
        public int program_g1_int47 { get; set; }
        public int program_g1_int46 { get; set; }
        public int program_g1_int45 { get; set; }
        public int program_g1_int44 { get; set; }
        public int program_g1_int43 { get; set; }
        public int program_g1_int42 { get; set; }
        public int program_g1_int41 { get; set; }
        public int program_g1_int40 { get; set; }
        public int program_g1_int39 { get; set; }
        public int program_g1_int38 { get; set; }
        public int program_g1_int37 { get; set; }
        public int program_g1_int36 { get; set; }
        public int program_g1_int35 { get; set; }
        public int program_g1_int34 { get; set; }
        public int program_g1_int33 { get; set; }
        public int program_g1_int32 { get; set; }
        public int program_g1_int31 { get; set; }
        public int program_g1_int30 { get; set; }
        public int program_g1_int29 { get; set; }
        public int program_g1_int28 { get; set; }
        public int program_g1_int27 { get; set; }
        public int program_g1_int26 { get; set; }
        public int program_g1_int25 { get; set; }
        public int program_g1_int24 { get; set; }
        public int program_g1_int23 { get; set; }
        public int program_g1_int22 { get; set; }
        public int program_g1_int21 { get; set; }
        public int program_g1_int20 { get; set; }
        public int program_g1_int19 { get; set; }
        public int program_g1_int18 { get; set; }
        public int program_g1_int17 { get; set; }
        public int program_g1_int16 { get; set; }
        public int program_g1_int15 { get; set; }
        public int program_g1_int14 { get; set; }
        public int program_g1_int13 { get; set; }
        public int program_g1_int12 { get; set; }
        public int program_g1_int11 { get; set; }
        public int program_g1_int10 { get; set; }
        public int program_g1_int9 { get; set; }
        public int program_g1_int8 { get; set; }
        public int program_g1_int7 { get; set; }
        public int program_g1_int6 { get; set; }
        public int program_g1_int5 { get; set; }
        public int program_g1_int4 { get; set; }
        public int program_g1_int3 { get; set; }
        public int program_g1_int2 { get; set; }
        public int program_g1_int1 { get; set; }
        public double temp_comfort { get; set; }
        public double temp_eco { get; set; }
        public int tipo_allarme_allarme_99 { get; set; }
        public int ts_allarme_99 { get; set; }
        public int tipo_allarme_allarme_98 { get; set; }
        public int ts_allarme_98 { get; set; }
        public int tipo_allarme_allarme_97 { get; set; }
        public int ts_allarme_97 { get; set; }
        public int tipo_allarme_allarme_96 { get; set; }
        public int ts_allarme_96 { get; set; }
        public int tipo_allarme_allarme_95 { get; set; }
        public int ts_allarme_95 { get; set; }
        public int tipo_allarme_allarme_94 { get; set; }
        public int ts_allarme_94 { get; set; }
        public int tipo_allarme_allarme_93 { get; set; }
        public int ts_allarme_93 { get; set; }
        public int tipo_allarme_allarme_92 { get; set; }
        public int ts_allarme_92 { get; set; }
        public int tipo_allarme_allarme_91 { get; set; }
        public int ts_allarme_91 { get; set; }
        public int tipo_allarme_allarme_90 { get; set; }
        public int ts_allarme_90 { get; set; }
        public int tipo_allarme_allarme_89 { get; set; }
        public int ts_allarme_89 { get; set; }
        public int tipo_allarme_allarme_88 { get; set; }
        public int ts_allarme_88 { get; set; }
        public int tipo_allarme_allarme_87 { get; set; }
        public int ts_allarme_87 { get; set; }
        public int tipo_allarme_allarme_86 { get; set; }
        public int ts_allarme_86 { get; set; }
        public int tipo_allarme_allarme_85 { get; set; }
        public int ts_allarme_85 { get; set; }
        public int tipo_allarme_allarme_84 { get; set; }
        public int ts_allarme_84 { get; set; }
        public int tipo_allarme_allarme_83 { get; set; }
        public int ts_allarme_83 { get; set; }
        public int tipo_allarme_allarme_82 { get; set; }
        public int ts_allarme_82 { get; set; }
        public int tipo_allarme_allarme_81 { get; set; }
        public int ts_allarme_81 { get; set; }
        public int tipo_allarme_allarme_80 { get; set; }
        public int ts_allarme_80 { get; set; }
        public int tipo_allarme_allarme_79 { get; set; }
        public int ts_allarme_79 { get; set; }
        public int tipo_allarme_allarme_78 { get; set; }
        public int ts_allarme_78 { get; set; }
        public int tipo_allarme_allarme_77 { get; set; }
        public int ts_allarme_77 { get; set; }
        public int tipo_allarme_allarme_76 { get; set; }
        public int ts_allarme_76 { get; set; }
        public int tipo_allarme_allarme_75 { get; set; }
        public int ts_allarme_75 { get; set; }
        public int tipo_allarme_allarme_74 { get; set; }
        public int ts_allarme_74 { get; set; }
        public int tipo_allarme_allarme_73 { get; set; }
        public int ts_allarme_73 { get; set; }
        public int tipo_allarme_allarme_72 { get; set; }
        public int ts_allarme_72 { get; set; }
        public int tipo_allarme_allarme_71 { get; set; }
        public int ts_allarme_71 { get; set; }
        public int tipo_allarme_allarme_70 { get; set; }
        public int ts_allarme_70 { get; set; }
        public int tipo_allarme_allarme_69 { get; set; }
        public int ts_allarme_69 { get; set; }
        public int tipo_allarme_allarme_68 { get; set; }
        public int ts_allarme_68 { get; set; }
        public int tipo_allarme_allarme_67 { get; set; }
        public int ts_allarme_67 { get; set; }
        public int tipo_allarme_allarme_66 { get; set; }
        public int ts_allarme_66 { get; set; }
        public int tipo_allarme_allarme_65 { get; set; }
        public int ts_allarme_65 { get; set; }
        public int tipo_allarme_allarme_64 { get; set; }
        public int ts_allarme_64 { get; set; }
        public int tipo_allarme_allarme_63 { get; set; }
        public int ts_allarme_63 { get; set; }
        public int tipo_allarme_allarme_62 { get; set; }
        public int ts_allarme_62 { get; set; }
        public int tipo_allarme_allarme_61 { get; set; }
        public int ts_allarme_61 { get; set; }
        public int tipo_allarme_allarme_60 { get; set; }
        public int ts_allarme_60 { get; set; }
        public int tipo_allarme_allarme_59 { get; set; }
        public int ts_allarme_59 { get; set; }
        public int tipo_allarme_allarme_58 { get; set; }
        public int ts_allarme_58 { get; set; }
        public int tipo_allarme_allarme_57 { get; set; }
        public int ts_allarme_57 { get; set; }
        public int tipo_allarme_allarme_56 { get; set; }
        public int ts_allarme_56 { get; set; }
        public int tipo_allarme_allarme_55 { get; set; }
        public int ts_allarme_55 { get; set; }
        public int tipo_allarme_allarme_54 { get; set; }
        public int ts_allarme_54 { get; set; }
        public int tipo_allarme_allarme_53 { get; set; }
        public int ts_allarme_53 { get; set; }
        public int tipo_allarme_allarme_52 { get; set; }
        public int ts_allarme_52 { get; set; }
        public int tipo_allarme_allarme_51 { get; set; }
        public int ts_allarme_51 { get; set; }
        public int tipo_allarme_allarme_50 { get; set; }
        public int ts_allarme_50 { get; set; }
        public int tipo_allarme_allarme_49 { get; set; }
        public int ts_allarme_49 { get; set; }
        public int tipo_allarme_allarme_48 { get; set; }
        public int ts_allarme_48 { get; set; }
        public int tipo_allarme_allarme_47 { get; set; }
        public int ts_allarme_47 { get; set; }
        public int tipo_allarme_allarme_46 { get; set; }
        public int ts_allarme_46 { get; set; }
        public int tipo_allarme_allarme_45 { get; set; }
        public int ts_allarme_45 { get; set; }
        public int tipo_allarme_allarme_44 { get; set; }
        public int ts_allarme_44 { get; set; }
        public int tipo_allarme_allarme_43 { get; set; }
        public int ts_allarme_43 { get; set; }
        public int tipo_allarme_allarme_42 { get; set; }
        public int ts_allarme_42 { get; set; }
        public int tipo_allarme_allarme_41 { get; set; }
        public int ts_allarme_41 { get; set; }
        public int tipo_allarme_allarme_40 { get; set; }
        public int ts_allarme_40 { get; set; }
        public int tipo_allarme_allarme_39 { get; set; }
        public int ts_allarme_39 { get; set; }
        public int tipo_allarme_allarme_38 { get; set; }
        public int ts_allarme_38 { get; set; }
        public int tipo_allarme_allarme_37 { get; set; }
        public int ts_allarme_37 { get; set; }
        public int tipo_allarme_allarme_36 { get; set; }
        public int ts_allarme_36 { get; set; }
        public int tipo_allarme_allarme_35 { get; set; }
        public int ts_allarme_35 { get; set; }
        public int tipo_allarme_allarme_34 { get; set; }
        public int ts_allarme_34 { get; set; }
        public int tipo_allarme_allarme_33 { get; set; }
        public int ts_allarme_33 { get; set; }
        public int tipo_allarme_allarme_32 { get; set; }
        public int ts_allarme_32 { get; set; }
        public int tipo_allarme_allarme_31 { get; set; }
        public int ts_allarme_31 { get; set; }
        public int tipo_allarme_allarme_30 { get; set; }
        public int ts_allarme_30 { get; set; }
        public int tipo_allarme_allarme_29 { get; set; }
        public int ts_allarme_29 { get; set; }
        public int tipo_allarme_allarme_28 { get; set; }
        public int ts_allarme_28 { get; set; }
        public int tipo_allarme_allarme_27 { get; set; }
        public int ts_allarme_27 { get; set; }
        public int tipo_allarme_allarme_26 { get; set; }
        public int ts_allarme_26 { get; set; }
        public int tipo_allarme_allarme_25 { get; set; }
        public int ts_allarme_25 { get; set; }
        public int tipo_allarme_allarme_24 { get; set; }
        public int ts_allarme_24 { get; set; }
        public int tipo_allarme_allarme_23 { get; set; }
        public int ts_allarme_23 { get; set; }
        public int tipo_allarme_allarme_22 { get; set; }
        public int ts_allarme_22 { get; set; }
        public int tipo_allarme_allarme_21 { get; set; }
        public int ts_allarme_21 { get; set; }
        public int tipo_allarme_allarme_20 { get; set; }
        public int ts_allarme_20 { get; set; }
        public int tipo_allarme_allarme_19 { get; set; }
        public int ts_allarme_19 { get; set; }
        public int tipo_allarme_allarme_18 { get; set; }
        public int ts_allarme_18 { get; set; }
        public int tipo_allarme_allarme_17 { get; set; }
        public int ts_allarme_17 { get; set; }
        public int tipo_allarme_allarme_16 { get; set; }
        public int ts_allarme_16 { get; set; }
        public int tipo_allarme_allarme_15 { get; set; }
        public int ts_allarme_15 { get; set; }
        public int tipo_allarme_allarme_14 { get; set; }
        public int ts_allarme_14 { get; set; }
        public int tipo_allarme_allarme_13 { get; set; }
        public int ts_allarme_13 { get; set; }
        public int tipo_allarme_allarme_12 { get; set; }
        public int ts_allarme_12 { get; set; }
        public int tipo_allarme_allarme_11 { get; set; }
        public int ts_allarme_11 { get; set; }
        public int tipo_allarme_allarme_10 { get; set; }
        public int ts_allarme_10 { get; set; }
        public int tipo_allarme_allarme_9 { get; set; }
        public int ts_allarme_9 { get; set; }
        public int tipo_allarme_allarme_8 { get; set; }
        public int ts_allarme_8 { get; set; }
        public int tipo_allarme_allarme_7 { get; set; }
        public int ts_allarme_7 { get; set; }
        public int tipo_allarme_allarme_6 { get; set; }
        public int ts_allarme_6 { get; set; }
        public int tipo_allarme_allarme_5 { get; set; }
        public int ts_allarme_5 { get; set; }
        public int tipo_allarme_allarme_4 { get; set; }
        public int ts_allarme_4 { get; set; }
        public int tipo_allarme_allarme_3 { get; set; }
        public int ts_allarme_3 { get; set; }
        public int tipo_allarme_allarme_2 { get; set; }
        public int ts_allarme_2 { get; set; }
        public int tipo_allarme_allarme_1 { get; set; }
        public int ts_allarme_1 { get; set; }
        public int tipo_allarme_allarme_0 { get; set; }
        public int ts_allarme_0 { get; set; }
        public int index_allarme { get; set; }
        public int num_allarmi { get; set; }
        public int cnt_serv_tempo_lav_tot { get; set; }
        public int cnt_serv_tempo_lav_p5 { get; set; }
        public int cnt_serv_tempo_lav_p4 { get; set; }
        public int cnt_serv_tempo_lav_p3 { get; set; }
        public int cnt_serv_tempo_lav_p2 { get; set; }
        public int cnt_serv_tempo_lav_p1 { get; set; }
        public int cnt_tot_tempo_lav_tot { get; set; }
        public int cnt_tot_tempo_lav_p5 { get; set; }
        public int cnt_tot_tempo_lav_p4 { get; set; }
        public int cnt_tot_tempo_lav_p3 { get; set; }
        public int cnt_tot_tempo_lav_p2 { get; set; }
        public int cnt_tot_tempo_lav_p1 { get; set; }
        public int num_accensioni { get; set; }
        public int cod_comp_4 { get; set; }
        public string banca_dati { get; set; }
        public int rev_banca_dati { get; set; }
        public int vel_bloc_bru2_core { get; set; }
        public int delta_usc_blocco_brush { get; set; }
        public int log_valv_3vie { get; set; }
        public double max_temp_cald_a20 { get; set; }
        public double min_temp_cald_a20 { get; set; }
        public double max_temp_cald_a19 { get; set; }
        public double min_temp_cald_a19 { get; set; }
        public int rit_fase_a20 { get; set; }
        public int rit_fase_a19 { get; set; }
        public double delta_temp_max_mand { get; set; }
        public double temp_max_mand { get; set; }
        public int soglia_blocco_mecc { get; set; }
        public int pres_pul_brush { get; set; }
        public int pos_ap_pul { get; set; }
        public double tempo_ril_blocco_mecc { get; set; }
        public int car_pel_colp_coc_car_rid { get; set; }
        public int car_pel_car_rid { get; set; }
        public int t_buon_funz_dec_act { get; set; }
        public int t_n_car_rid_inc_act { get; set; }
        public int t_n_car_rid_sp { get; set; }
        public int int_colp_coc_car_rid { get; set; }
        public int dur_colp_coc_car_rid { get; set; }
        public int t_car_rid { get; set; }
        public int t_n_c_rid_coppia { get; set; }
        public int inc_val_flu_perc { get; set; }
        public int inc_val_flu { get; set; }
        public int n_car_rid_act { get; set; }
        public int n_car_rid_sp { get; set; }
        public int n_cicli_rid_coppia { get; set; }
        public int dur_lim { get; set; }
        public int n_ore_pot_el { get; set; }
        public int pot_lim { get; set; }
        public double lim_temp_pan { get; set; }
        public int s_max_val_flu_allarme_a14 { get; set; }
        public int s_min_val_flu_allarme_a14 { get; set; }
        public int var_flu_allarme_2 { get; set; }
        public int var_flu_allarme_1 { get; set; }
        public int car_pel_allarme_2 { get; set; }
        public int car_pel_allarme_1 { get; set; }
        public int v_ven_fumi_allarme_a05 { get; set; }
        public int v_ven_fumi_allarme_a08 { get; set; }
        public int v_ven_fumi_allarme_2 { get; set; }
        public int v_ven_fumi_allarme_1 { get; set; }
        public int t_bkout { get; set; }
        public int tout_cic { get; set; }
        public int rit_sbloc_coc { get; set; }
        public int rit_a22 { get; set; }
        public int rit_a21 { get; set; }
        public int rit_a14 { get; set; }
        public int rit_a13 { get; set; }
        public int rit_a12 { get; set; }
        public int rit_a09 { get; set; }
        public int rit_a08 { get; set; }
        public int rit_a05 { get; set; }
        public int rit_a04 { get; set; }
        public int rit_a03 { get; set; }
        public int rit_a02 { get; set; }
        public int dur_allarme_2 { get; set; }
        public int dur_allarme_1 { get; set; }
        public int rit_ing_standby { get; set; }
        public int rit_usc_standby { get; set; }
        public int int_col_coc { get; set; }
        public int dur_col_coc { get; set; }
        public int car_pel_pot { get; set; }
        public int colp_coc_pot { get; set; }
        public int n_max_riarmi_press { get; set; }
        public int rit_riarmo_press { get; set; }
        public int abi_agg_pot_ven { get; set; }
        public int abi_ven4_tlc_app { get; set; }
        public int abi_ven3_tlc_app { get; set; }
        public int abi_ven2_tlc_app { get; set; }
        public int abi_ven1_tlc_app { get; set; }
        public int vis_ven4_tlc_app { get; set; }
        public int vis_ven3_tlc_app { get; set; }
        public int vis_ven2_tlc_app { get; set; }
        public int vis_ven1_tlc_app { get; set; }
        public int abi_auto_ven4 { get; set; }
        public int abi_auto_ven3 { get; set; }
        public int abi_auto_ven2 { get; set; }
        public int abi_auto_ven1 { get; set; }
        public int abi_off_ven4 { get; set; }
        public int abi_off_ven3 { get; set; }
        public int abi_off_ven2 { get; set; }
        public int abi_off_ven1 { get; set; }
        public int pres_ven4 { get; set; }
        public int pres_ven3 { get; set; }
        public int pres_ven2 { get; set; }
        public int pres_ven1 { get; set; }
        public int liv_ven_COM_v4_p5 { get; set; }
        public int liv_ven_COM_v4_p4 { get; set; }
        public int liv_ven_COM_v4_p3 { get; set; }
        public int liv_ven_COM_v4_p2 { get; set; }
        public int liv_ven_COM_v4_p1 { get; set; }
        public int liv_ven_COM_v3_p5 { get; set; }
        public int liv_ven_COM_v3_p4 { get; set; }
        public int liv_ven_COM_v3_p3 { get; set; }
        public int liv_ven_COM_v3_p2 { get; set; }
        public int liv_ven_COM_v3_p1 { get; set; }
        public int liv_ven_COM_v2_p5 { get; set; }
        public int liv_ven_COM_v2_p4 { get; set; }
        public int liv_ven_COM_v2_p3 { get; set; }
        public int liv_ven_COM_v2_p2 { get; set; }
        public int liv_ven_COM_v2_p1 { get; set; }
        public int liv_ven_COM_v1_p5 { get; set; }
        public int liv_ven_COM_v1_p4 { get; set; }
        public int liv_ven_COM_v1_p3 { get; set; }
        public int liv_ven_COM_v1_p2 { get; set; }
        public int liv_ven_COM_v1_p1 { get; set; }
        public int liv_ven_OVE_v4_p5 { get; set; }
        public int liv_ven_OVE_v4_p4 { get; set; }
        public int liv_ven_OVE_v4_p3 { get; set; }
        public int liv_ven_OVE_v4_p2 { get; set; }
        public int liv_ven_OVE_v4_p1 { get; set; }
        public int liv_ven_OVE_v3_p5 { get; set; }
        public int liv_ven_OVE_v3_p4 { get; set; }
        public int liv_ven_OVE_v3_p3 { get; set; }
        public int liv_ven_OVE_v3_p2 { get; set; }
        public int liv_ven_OVE_v3_p1 { get; set; }
        public int liv_ven_OVE_v2_p5 { get; set; }
        public int liv_ven_OVE_v2_p4 { get; set; }
        public int liv_ven_OVE_v2_p3 { get; set; }
        public int liv_ven_OVE_v2_p2 { get; set; }
        public int liv_ven_OVE_v2_p1 { get; set; }
        public int liv_ven_OVE_v1_p5 { get; set; }
        public int liv_ven_OVE_v1_p4 { get; set; }
        public int liv_ven_OVE_v1_p3 { get; set; }
        public int liv_ven_OVE_v1_p2 { get; set; }
        public int liv_ven_OVE_v1_p1 { get; set; }
        public int liv_ven_DYN_v4_p5 { get; set; }
        public int liv_ven_DYN_v4_p4 { get; set; }
        public int liv_ven_DYN_v4_p3 { get; set; }
        public int liv_ven_DYN_v4_p2 { get; set; }
        public int liv_ven_DYN_v4_p1 { get; set; }
        public int liv_ven_DYN_v3_p5 { get; set; }
        public int liv_ven_DYN_v3_p4 { get; set; }
        public int liv_ven_DYN_v3_p3 { get; set; }
        public int liv_ven_DYN_v3_p2 { get; set; }
        public int liv_ven_DYN_v3_p1 { get; set; }
        public int liv_ven_DYN_v2_p5 { get; set; }
        public int liv_ven_DYN_v2_p4 { get; set; }
        public int liv_ven_DYN_v2_p3 { get; set; }
        public int liv_ven_DYN_v2_p2 { get; set; }
        public int liv_ven_DYN_v2_p1 { get; set; }
        public int liv_ven_DYN_v1_p5 { get; set; }
        public int liv_ven_DYN_v1_p4 { get; set; }
        public int liv_ven_DYN_v1_p3 { get; set; }
        public int liv_ven_DYN_v1_p2 { get; set; }
        public int liv_ven_DYN_v1_p1 { get; set; }
        public int liv_ven_MAN_v4_p5 { get; set; }
        public int liv_ven_MAN_v4_p4 { get; set; }
        public int liv_ven_MAN_v4_p3 { get; set; }
        public int liv_ven_MAN_v4_p2 { get; set; }
        public int liv_ven_MAN_v4_p1 { get; set; }
        public int liv_ven_MAN_v3_p5 { get; set; }
        public int liv_ven_MAN_v3_p4 { get; set; }
        public int liv_ven_MAN_v3_p3 { get; set; }
        public int liv_ven_MAN_v3_p2 { get; set; }
        public int liv_ven_MAN_v3_p1 { get; set; }
        public int liv_ven_MAN_v2_p5 { get; set; }
        public int liv_ven_MAN_v2_p4 { get; set; }
        public int liv_ven_MAN_v2_p3 { get; set; }
        public int liv_ven_MAN_v2_p2 { get; set; }
        public int liv_ven_MAN_v2_p1 { get; set; }
        public int liv_ven_MAN_v1_p5 { get; set; }
        public int liv_ven_MAN_v1_p4 { get; set; }
        public int liv_ven_MAN_v1_p3 { get; set; }
        public int liv_ven_MAN_v1_p2 { get; set; }
        public int liv_ven_MAN_v1_p1 { get; set; }
        public double ist_att_dis_ven5 { get; set; }
        public double ist_att_dis_ven3 { get; set; }
        public double ist_att_dis_ven2 { get; set; }
        public double ist_att_dis_ven1 { get; set; }
        public int car_pel_test_sbloc_coc { get; set; }
        public int vel_bloc_bru2 { get; set; }
        public int vel_bloc_bru1 { get; set; }
        public int delta_riv_bloc_bru_1 { get; set; }
        public int t_riv_bloc_bru3 { get; set; }
        public int t_riv_bloc_bru2 { get; set; }
        public int t_riv_bloc_bru1 { get; set; }
        public int t_autor { get; set; }
        public int autor_min { get; set; }
        public int autor_plus { get; set; }
        public int t_rampa { get; set; }
        public int tipo_mr { get; set; }
        public int mr_out_min { get; set; }
        public int mr_ti { get; set; }
        public int mr_kp { get; set; }
        public int t_coc_tot { get; set; }
        public int max_v_coc { get; set; }
        public int min_v_coc { get; set; }
        public int est_out_min { get; set; }
        public int est_ti { get; set; }
        public int est_kp { get; set; }
        public int max_v_est { get; set; }
        public int min_v_est { get; set; }
        public int mod_ris_pel { get; set; }
        public int pres_pul { get; set; }
        public int max_pot_mod_COM { get; set; }
        public int max_pot_mod_OVE { get; set; }
        public int max_pot_mod_DYN { get; set; }
        public int max_pot_mod_MAN { get; set; }
        public int t_aut_pellet { get; set; }
        public double s_temp_riavvio_fumi_allarme { get; set; }
        public int t_ult_spegn { get; set; }
        public int ore_serv { get; set; }
        public int t_funz_sil { get; set; }
        public int tipo_app { get; set; }
        public int cod_comp_3 { get; set; }
        public double temp_a02_lav { get; set; }
        public double ist_a02_acc { get; set; }
        public int tempo_post_circ_alarm { get; set; }
        public int tempo_post_circ { get; set; }
        public int att_antigelo { get; set; }
        public double delta_t_boiler_spe_pompa { get; set; }
        public double delta_t_boiler_acc_pompa { get; set; }
        public double temp_antigelo { get; set; }
        public double ist_lim_temp_acqua { get; set; }
        public double lim_temp_acqua { get; set; }
        public int max_pompa { get; set; }
        public int min_pompa { get; set; }
        public double ist_pos_pompa { get; set; }
        public double ist_neg_pompa { get; set; }
        public int lim_max_offset_fl { get; set; }
        public int lim_min_offset_fl { get; set; }
        public int offset_pos_zero_pul { get; set; }
        public int val_flu_pre_sp { get; set; }
        public int car_pel_pre_sp { get; set; }
        public int v_vent_fumi_pre_sp { get; set; }
        public int t_pre_sp { get; set; }
        public int val_flu_anticon { get; set; }
        public int car_pel_anticon { get; set; }
        public int v_vent_fumi_anticon { get; set; }
        public int t_anticon { get; set; }
        public double adj_sonda_fumi { get; set; }
        public int v_ven_fumi_standby { get; set; }
        public int pos_rip_brac { get; set; }
        public int n_pul_brac { get; set; }
        public int err_act_pul_mecc { get; set; }
        public int s_ven_fumi_pul_mec { get; set; }
        public int t_cor_pul { get; set; }
        public int t_max_lav_pul_mec { get; set; }
        public int autoreg { get; set; }
        public int ti_act { get; set; }
        public int kp_act { get; set; }
        public int act_acc { get; set; }
        public int act { get; set; }
        public int scot_coc_a12 { get; set; }
        public int val_flu_allarme_a05 { get; set; }
        public int car_pel_allarme_a05 { get; set; }
        public int car_pel_sbl_coc { get; set; }
        public int v_ven_fumi_riarmo_allarme_a21 { get; set; }
        public double s_max_temp_amb_allarme_a22 { get; set; }
        public double s_min_temp_amb_allarme_a22 { get; set; }
        public double temp_sch_allarme_a13 { get; set; }
        public double temp_sch_pre_allarme_a13 { get; set; }
        public double temp_fumi_allarme_a09 { get; set; }
        public double ist_fumi_pre_allarme_a04 { get; set; }
        public double temp_fumi_allarme_a04 { get; set; }
        public double temp_fumi_pre_allarme_a04 { get; set; }
        public int ven_mod_pow { get; set; }
        public int ven_sta_allarmi_ven4 { get; set; }
        public int ven_sta_allarmi_ven3 { get; set; }
        public int ven_sta_allarmi_ven2 { get; set; }
        public int ven_sta_allarmi_ven1 { get; set; }
        public int ven_sta_ven4 { get; set; }
        public int ven_sta_ven3 { get; set; }
        public int ven_sta_ven2 { get; set; }
        public int ven_sta_ven1 { get; set; }
        public int v_ven4_v5_ada { get; set; }
        public int v_ven4_v4_ada { get; set; }
        public int v_ven4_v3_ada { get; set; }
        public int v_ven4_v2_ada { get; set; }
        public int v_ven4_v1_ada { get; set; }
        public int v_ven4_v0_ada { get; set; }
        public int v_ven3_v5_ada { get; set; }
        public int v_ven3_v4_ada { get; set; }
        public int v_ven3_v3_ada { get; set; }
        public int v_ven3_v2_ada { get; set; }
        public int v_ven3_v1_ada { get; set; }
        public int v_ven3_v0_ada { get; set; }
        public int v_ven2_v5_ada { get; set; }
        public int v_ven2_v4_ada { get; set; }
        public int v_ven2_v3_ada { get; set; }
        public int v_ven2_v2_ada { get; set; }
        public int v_ven2_v1_ada { get; set; }
        public int v_ven2_v0_ada { get; set; }
        public int v_ven1_v5_ada { get; set; }
        public int v_ven1_v4_ada { get; set; }
        public int v_ven1_v3_ada { get; set; }
        public int v_ven1_v2_ada { get; set; }
        public int v_ven1_v1_ada { get; set; }
        public int v_ven1_v0_ada { get; set; }
        public int v_ven4_v5 { get; set; }
        public int v_ven4_v4 { get; set; }
        public int v_ven4_v3 { get; set; }
        public int v_ven4_v2 { get; set; }
        public int v_ven4_v1 { get; set; }
        public int v_ven4_v0 { get; set; }
        public int v_ven3_v5 { get; set; }
        public int v_ven3_v4 { get; set; }
        public int v_ven3_v3 { get; set; }
        public int v_ven3_v2 { get; set; }
        public int v_ven3_v1 { get; set; }
        public int v_ven3_v0 { get; set; }
        public int v_ven2_v5 { get; set; }
        public int v_ven2_v4 { get; set; }
        public int v_ven2_v3 { get; set; }
        public int v_ven2_v2 { get; set; }
        public int v_ven2_v1 { get; set; }
        public int v_ven2_v0 { get; set; }
        public int v_ven1_v5 { get; set; }
        public int v_ven1_v4 { get; set; }
        public int v_ven1_v3 { get; set; }
        public int v_ven1_v2 { get; set; }
        public int v_ven1_v1 { get; set; }
        public int v_ven1_v0 { get; set; }
        public int val_k_calc_pot_max { get; set; }
        public double sogl_az_ven4 { get; set; }
        public double sogl_az_ven3 { get; set; }
        public double sogl_az_ven2 { get; set; }
        public double sogl_az_ven1 { get; set; }
        public int mod_ada_on { get; set; }
        public int tipo_pul_pot5 { get; set; }
        public int tipo_pul_pot4 { get; set; }
        public int tipo_pul_pot3 { get; set; }
        public int tipo_pul_pot2 { get; set; }
        public int tipo_pul_pot1 { get; set; }
        public int val_flu_pot5_ada { get; set; }
        public int val_flu_pot4_ada { get; set; }
        public int val_flu_pot3_ada { get; set; }
        public int val_flu_pot2_ada { get; set; }
        public int val_flu_pot1_ada { get; set; }
        public int val_flu_pot5 { get; set; }
        public int val_flu_pot4 { get; set; }
        public int val_flu_pot3 { get; set; }
        public int val_flu_pot2 { get; set; }
        public int val_flu_pot1 { get; set; }
        public int car_pel_pot5_ada { get; set; }
        public int car_pel_pot4_ada { get; set; }
        public int car_pel_pot3_ada { get; set; }
        public int car_pel_pot2_ada { get; set; }
        public int car_pel_pot1_ada { get; set; }
        public int car_pel_pot5 { get; set; }
        public int car_pel_pot4 { get; set; }
        public int car_pel_pot3 { get; set; }
        public int car_pel_pot2 { get; set; }
        public int car_pel_pot1 { get; set; }
        public int v_ven_fumi_pot5_ada { get; set; }
        public int v_ven_fumi_pot4_ada { get; set; }
        public int v_ven_fumi_pot3_ada { get; set; }
        public int v_ven_fumi_pot2_ada { get; set; }
        public int v_ven_fumi_pot1_ada { get; set; }
        public int v_ven_fumi_pot5 { get; set; }
        public int v_ven_fumi_pot4 { get; set; }
        public int v_ven_fumi_pot3 { get; set; }
        public int v_ven_fumi_pot2 { get; set; }
        public int v_ven_fumi_pot1 { get; set; }
        public int int_t_cam_pot { get; set; }
        public int int_pul_pot5_ada { get; set; }
        public int int_pul_pot4_ada { get; set; }
        public int int_pul_pot3_ada { get; set; }
        public int int_pul_pot2_ada { get; set; }
        public int int_pul_pot1_ada { get; set; }
        public int int_pul_pot5 { get; set; }
        public int int_pul_pot4 { get; set; }
        public int int_pul_pot3 { get; set; }
        public int int_pul_pot2 { get; set; }
        public int int_pul_pot1 { get; set; }
        public double temp_fumi_pot5_ada { get; set; }
        public double temp_fumi_pot4_ada { get; set; }
        public double temp_fumi_pot3_ada { get; set; }
        public double temp_fumi_pot2_ada { get; set; }
        public double temp_fumi_pot1_ada { get; set; }
        public double temp_fumi_pot5 { get; set; }
        public double temp_fumi_pot4 { get; set; }
        public double temp_fumi_pot3 { get; set; }
        public double temp_fumi_pot2 { get; set; }
        public double temp_fumi_pot1 { get; set; }
        public int val_flu_raff { get; set; }
        public int car_pel_raff { get; set; }
        public int v_ven_fumi_raff { get; set; }
        public double temp_fumi_st_spenta { get; set; }
        public int val_flu_spegn { get; set; }
        public int car_pel_spegn { get; set; }
        public int v_ven_fumi_spegn { get; set; }
        public int t_spegn { get; set; }
        public int va_flu_pul_l_ada { get; set; }
        public int va_flu_pul_h_ada { get; set; }
        public int va_flu_pul_l { get; set; }
        public int va_flu_pul_h { get; set; }
        public int car_pel_pul_l_ada { get; set; }
        public int car_pel_pul_h_ada { get; set; }
        public int car_pel_pul_l { get; set; }
        public int car_pel_pul_h { get; set; }
        public int v_ven_fumi_pul_l_ada { get; set; }
        public int v_ven_fumi_pul_h_ada { get; set; }
        public int v_ven_fumi_pul_l { get; set; }
        public int v_ven_fumi_pul_h { get; set; }
        public int dur_pul_h_ada { get; set; }
        public int dur_pul_l_ada { get; set; }
        public int dur_pul_l { get; set; }
        public int dur_pul_h { get; set; }
        public int val_flu_stab { get; set; }
        public int car_pel_stab { get; set; }
        public int v_ven_fumi_stab { get; set; }
        public int t_stab { get; set; }
        public int val_flu_st2_ca { get; set; }
        public int val_flu_st2_fr { get; set; }
        public int val_flu_st1_ca { get; set; }
        public int val_flu_st1_fr { get; set; }
        public int car_pel_st2_ca { get; set; }
        public int car_pel_st2_fr { get; set; }
        public int car_pel_st1_ca { get; set; }
        public int car_pel_st1_fr { get; set; }
        public int v_vent_fumi_st2_ca { get; set; }
        public int v_vent_fumi_st2_fr { get; set; }
        public int v_vent_fumi_st1_ca { get; set; }
        public int v_vent_fumi_st1_fr { get; set; }
        public int t_max_st2_ca { get; set; }
        public int t_max_st2_fr { get; set; }
        public int t_max_st1_ca { get; set; }
        public int t_max_st1_fr { get; set; }
        public double temp_fumi_acc { get; set; }
        public double delta_t_st2_ca { get; set; }
        public double delta_t_st2_fr { get; set; }
        public int val_flu_load_ca { get; set; }
        public int val_flu_load_fr { get; set; }
        public int car_pel_load_ca { get; set; }
        public int car_pel_load_fr { get; set; }
        public int v_vent_fumi_load_ca { get; set; }
        public int v_vent_fumi_load_fr { get; set; }
        public int t_car_pel_man { get; set; }
        public int t_fase_load_ca { get; set; }
        public int t_fase_load_fr { get; set; }
        public int v_vent_fumi_clean_ca { get; set; }
        public int v_vent_fumi_clean_fr { get; set; }
        public int t_fase_clean_ca { get; set; }
        public int t_fase_clean_fr { get; set; }
        public int ric_flu_pos7 { get; set; }
        public int ric_flu_pos6 { get; set; }
        public int ric_flu_pos5 { get; set; }
        public int ric_flu_pos4 { get; set; }
        public int ric_flu_pos3 { get; set; }
        public int ric_flu_pos2 { get; set; }
        public int ric_flu_pos1 { get; set; }
        public int ric_pel_pos7 { get; set; }
        public int ric_pel_pos6 { get; set; }
        public int ric_pel_pos5 { get; set; }
        public int ric_pel_pos4 { get; set; }
        public int ric_pel_pos3 { get; set; }
        public int ric_pel_pos2 { get; set; }
        public int ric_pel_pos1 { get; set; }
        public int ric_asp_pos7 { get; set; }
        public int ric_asp_pos6 { get; set; }
        public int ric_asp_pos5 { get; set; }
        public int ric_asp_pos4 { get; set; }
        public int ric_asp_pos3 { get; set; }
        public int ric_asp_pos2 { get; set; }
        public int ric_asp_pos1 { get; set; }
        public int pos_ric_flu { get; set; }
        public int pos_ric_pel { get; set; }
        public int pos_ric_asp { get; set; }
        public int cod_comp_2 { get; set; }
        public int cod_comp_1 { get; set; }
        public double soglia_temp_cons_cald { get; set; }
        public int conf_rele_aux { get; set; }
        public double delta_cald_puffer { get; set; }
        public double delta_cald_boiler { get; set; }
        public int conf_imp { get; set; }
        public double set_puffer { get; set; }
        public double ist_pos_puffer { get; set; }
        public double ist_neg_puffer { get; set; }
        public int max_pot_idro { get; set; }
        public int est_inv { get; set; }
        public int ingr_fluss { get; set; }
        public int ingr_ntc3 { get; set; }
        public int ingr_ntc2 { get; set; }
        public double set_san { get; set; }
        public double ist_pos_boiler { get; set; }
        public double ist_neg_boiler { get; set; }
        public double set_boiler { get; set; }
        public double set_cald { get; set; }
        public double ist_pos_cald { get; set; }
        public double ist_neg_cald { get; set; }
        public double temp_min_circ_on { get; set; }
        public int paral_disp { get; set; }
        public int ingr_amb { get; set; }
        public int pul_brac { get; set; }
        public int sens_liv_pellet { get; set; }
        public int att_eco { get; set; }
        public int set_vent_v4 { get; set; }
        public int set_vent_v3 { get; set; }
        public int set_vent_v2 { get; set; }
        public int set_vent_v1 { get; set; }
        public double set_amb3 { get; set; }
        public double set_amb2 { get; set; }
        public double set_amb1 { get; set; }
        public double ist_eco_pos_amb { get; set; }
        public double ist_eco_neg_amb { get; set; }
        public double ist_pos_amb { get; set; }
        public double ist_neg_amb { get; set; }
        public int toni_buzz { get; set; }
        public int t_standby_disp { get; set; }
        public int lum_disp { get; set; }
        public int am_pm_param { get; set; }
        public int coclea_mod_continuo { get; set; }
        public int att_ora_leg { get; set; }
        public int silent { get; set; }
        public int set_pot_man { get; set; }
        public int c_or_f { get; set; }
        public int mod_funz { get; set; }
        public int lingua { get; set; }
        public long SensorDataTimestamp { get; set; }
        public string UniqueCode { get; set; }
        public string TenantId { get; set; }
    }

}
