using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nuboj.Archiver.ETL.Saver.Models
{
    public class Status
    {
        // Guid aggiunto da Andrea Zanetti come PK
        [Key]
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string SensorDataType { get; set; }
        public int cont_tot_t_lav5_h { get; set; }
        public int cont_tot_t_lav4_h { get; set; }
        public int cont_tot_t_lav3_h { get; set; }
        public int cont_tot_t_lav2_h { get; set; }
        public int cont_tot_t_lav1_h { get; set; }
        public int cont_tot_t_lavoro_h { get; set; }
        public int ore_service_h { get; set; }
        public int ScheduledTurnOffTimestamp { get; set; }
        public int cod_spg_imp { get; set; }
        public int cod_reset_conf { get; set; }
        public int cod_clear_board { get; set; }
        public int zero_brush { get; set; }
        public int cod_test_disp { get; set; }
        public int down_firm { get; set; }
        public string nome_banca_dati_sel { get; set; }
        public int ind_sel_nome_banca_dati { get; set; }
        public int cod_for_spe_mqtt { get; set; }
        public int cod_zero_sens_press { get; set; }
        public int cod_salta_acc { get; set; }
        public int cod_fil_test_rap { get; set; }
        public int reset_boot_pc { get; set; }
        public int reset_storico_allarmi { get; set; }
        public int reset_def_params { get; set; }
        public int com_inv_pos_bruciatore { get; set; }
        public int com_test_wifi { get; set; }
        public int com_skip_fase_op { get; set; }
        public int com_test_freddo { get; set; }
        public int com_canc_cont_par { get; set; }
        public int com_es_car_coclea { get; set; }
        public int com_forza_spegn { get; set; }
        public int com_reset_manut_CAT { get; set; }
        public int com_reset_allarm { get; set; }
        public int com_on_off { get; set; }
        public int tempo_sleep { get; set; }
        public int set_orodatario { get; set; }
        public int am_pm { get; set; }
        public int giorno_sett { get; set; }
        public int secondi { get; set; }
        public int minuti { get; set; }
        public int ore { get; set; }
        public int anno { get; set; }
        public int mese { get; set; }
        public int giorno { get; set; }
        public int temp_ingr_standby { get; set; }
        public int feed_pompa { get; set; }
        public int freq_feed_pompa { get; set; }
        public bool disp_but_acc { get; set; }
        public bool disp_but_plus { get; set; }
        public bool disp_but_set_prog { get; set; }
        public bool disp_but_vent { get; set; }
        public bool disp_but_crono { get; set; }
        public bool disp_but_min { get; set; }
        public bool disp_but_eco { get; set; }
        public int cont_car_rid_act { get; set; }
        public int cont_car_rid_sp { get; set; }
        public int act_set_pot5 { get; set; }
        public int act_set_pot4 { get; set; }
        public int act_set_pot3 { get; set; }
        public int act_set_pot2 { get; set; }
        public int act_set_pot1 { get; set; }
        public int cont_rid_cop { get; set; }
        public int fase_core { get; set; }
        public int t_int_pul { get; set; }
        public int t_dur_lim { get; set; }
        public int t_dur_pul { get; set; }
        public int CRC16_NVM { get; set; }
        public int dia_CRC16_comp_info { get; set; }
        public int dia_res_cau { get; set; }
        public bool pc_con { get; set; }
        public bool app_con { get; set; }
        public bool pan_con { get; set; }
        public int ore_service { get; set; }
        public int cont_ser_t_lavoro { get; set; }
        public int cont_ser_t_lav5 { get; set; }
        public int cont_ser_t_lav4 { get; set; }
        public int cont_ser_t_lav3 { get; set; }
        public int cont_ser_t_lav2 { get; set; }
        public int cont_ser_t_lav1 { get; set; }
        public int cont_tot_t_lavoro { get; set; }
        public int cont_tot_t_lav5 { get; set; }
        public int cont_tot_t_lav4 { get; set; }
        public int cont_tot_t_lav3 { get; set; }
        public int cont_tot_t_lav2 { get; set; }
        public int cont_tot_t_lav1 { get; set; }
        public int cont_tot_n_acc { get; set; }
        public bool req_heating { get; set; }
        public bool req_san { get; set; }
        public bool spg_enabled { get; set; }
        public bool ant_enabled { get; set; }
        public bool sp_disost { get; set; }
        public bool lim_in_cor { get; set; }
        public bool colp_coclea { get; set; }
        public bool temp_pan_h { get; set; }
        public bool motorid_guasto { get; set; }
        public bool riarmo_press { get; set; }
        public bool acc_caldo { get; set; }
        public bool adaptive_on { get; set; }
        public bool power_enabled { get; set; }
        public bool bd_missing { get; set; }
        public bool sensirion_pres { get; set; }
        public bool coclea_cont { get; set; }
        public bool check_strut { get; set; }
        public bool def_ee_rip { get; set; }
        public bool def_par_rip { get; set; }
        public bool check_fus { get; set; }
        public bool temp_scheda_high { get; set; }
        public bool clean_in_prog { get; set; }
        public bool temp_fumi_high { get; set; }
        public bool clean_air_in_prog { get; set; }
        public bool sleep_enabled { get; set; }
        public bool crono_enabled { get; set; }
        public bool silent_enabled { get; set; }
        public int wifi_status { get; set; }
        public bool ris_pellet { get; set; }
        public bool bat_back { get; set; }
        public bool man_cat { get; set; }
        public int num_banche_dati { get; set; }
        public int tempo_ciclo { get; set; }
        public int t_power { get; set; }
        public int mod_lav_att { get; set; }
        public int sbloc_mr_bl { get; set; }
        public int pot_max { get; set; }
        public double temp_stop_pompa { get; set; }
        public double temp_set_caldaia { get; set; }
        public int auto_pellet { get; set; }
        public double temp_amb_can3 { get; set; }
        public double temp_amb_can2 { get; set; }
        public double temp_amb_can1 { get; set; }
        public double temp_amb_install { get; set; }
        public int index_vel_v4 { get; set; }
        public int index_vel_v3 { get; set; }
        public int index_vel_v2 { get; set; }
        public int index_vel_v1 { get; set; }
        public int potenza_att { get; set; }
        public int tipo_allarme { get; set; }
        public int stato_sec_stufa { get; set; }
        public int stato_stufa { get; set; }
        public int sub_sub_fase_op { get; set; }
        public int sub_fase_op { get; set; }
        public int fase_op { get; set; }
        public double pol_pul_brush_set { get; set; }
        public double pol_pul_brush { get; set; }
        public int sr3_progr_comunicazioni { get; set; }
        public int sr3_umidita { get; set; }
        public int sr3_qualita_aria { get; set; }
        public double sr3_temp { get; set; }
        public int sr2_progr_comunicazioni { get; set; }
        public int sr2_umidita { get; set; }
        public int sr2_qualita_aria { get; set; }
        public double sr2_temp { get; set; }
        public int sr1_progr_comunicazioni { get; set; }
        public int sr1_umidita { get; set; }
        public int sr1_qualita_aria { get; set; }
        public double sr1_temp { get; set; }
        public bool led_rgb_b { get; set; }
        public bool led_rgb_v { get; set; }
        public bool led_rgb_r { get; set; }
        public bool led_g { get; set; }
        public bool led_r { get; set; }
        public bool dir_brush3 { get; set; }
        public bool dir_brush2 { get; set; }
        public bool motorid_air { get; set; }
        public bool exit_rele_sic { get; set; }
        public bool exit_cica { get; set; }
        public bool dir_brush1 { get; set; }
        public bool exit_estr_cen { get; set; }
        public bool exit_turbolat { get; set; }
        public bool stato_exit_pomp_ext { get; set; }
        public bool stato_valv_ext { get; set; }
        public bool stato_exit_cald_aus { get; set; }
        public bool stato_exit_all_rem { get; set; }
        public bool stato_exit_ozon { get; set; }
        public bool stato_exit_ion { get; set; }
        public bool stato_can_acc { get; set; }
        public bool stato_valv { get; set; }
        public int pompa { get; set; }
        public int ventola_scamb4 { get; set; }
        public int ventola_scamb3 { get; set; }
        public int ventola_scamb2 { get; set; }
        public int ventola_scamb1 { get; set; }
        public int uscita_ventola_fumi { get; set; }
        public int vel_real_ventola_fumi { get; set; }
        public int vel_imp_ventola_fumi { get; set; }
        public int uscita_coclea { get; set; }
        public int vel_real_coclea { get; set; }
        public int vel_imp_coclea { get; set; }
        public bool term_boll { get; set; }
        public bool term_puff { get; set; }
        public bool ing_term_amb3 { get; set; }
        public bool ing_term_amb2 { get; set; }
        public bool ing_term_amb1 { get; set; }
        public bool sens_liv_pel { get; set; }
        public bool cont_fine_pul { get; set; }
        public bool fluss_acq { get; set; }
        public bool fluss_san { get; set; }
        public bool cont_dom { get; set; }
        public bool stato_term_sic_acq { get; set; }
        public bool stato_press_fumi { get; set; }
        public bool stato_term_sic_pel { get; set; }
        public double flusso_acqua1 { get; set; }
        public int pressione_acqua { get; set; }
        public int pressione_imp { get; set; }
        public int pressione { get; set; }
        public int pressione_pascal { get; set; }
        public double temp_pan { get; set; }
        public double temp_termocoppia_imp { get; set; }
        public double temp_termocoppia1 { get; set; }
        public double temp_sonda_acc { get; set; }
        public double temp_sonda_est { get; set; }
        public double temp_bollitore { get; set; }
        public double temp_scheda { get; set; }
        public double temp_puffer { get; set; }
        public double temp_caldaia { get; set; }
        public double temp_NTC3 { get; set; }
        public double temp_NTC2 { get; set; }
        public double temp_NTC1 { get; set; }
        public long SensorDataTimestamp { get; set; }
        public string UniqueCode { get; set; }
        public string TenantId { get; set; }
    }

}
